import "../styles/globals.css";
import { MoralisProvider } from "react-moralis";
import Head from "next/head";
import Header from "../components/Header";
import { NotificationProvider } from "web3uikit";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>PNS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <MoralisProvider initializeOnMount={false}>
        <NotificationProvider>
          <Header />
          <Component {...pageProps} />
        </NotificationProvider>
      </MoralisProvider>
      <footer className="absolute bottom-0 left-2 ">
        <p>
          <a target="_blank" href="https://twitter.com/harendrashakya_">
            © Harendra Shakya
          </a>
        </p>
      </footer>
    </div>
  );
}

export default MyApp;
